/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppRoast {
    id: string;
    content: string;
    appId: string;
    submitter?: Principal;
    anonymous: boolean;
    timestamp: bigint;
}
export interface AnalyticsData {
    pageTraffic: Array<PageTraffic>;
    totalProfiles: bigint;
    totalPageVisits: bigint;
    profileCreations: Array<bigint>;
    totalAppsShared: bigint;
}
export interface Comment {
    id: string;
    content: string;
    author: Principal;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PageTraffic {
    visitCount: bigint;
    pageType: PageType;
    timestamp: bigint;
}
export interface AppShowcase {
    id: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    hashtags: Array<string>;
    appName: string;
    description: string;
    isDemo: boolean;
    likes: bigint;
    timestamp: bigint;
    category: string;
    liveLink: string;
    comments: Array<Comment>;
    updateDescription?: string;
    updateTimestamp?: bigint;
}
export interface ExternalLink {
    url: string;
    linkLabel: string;
}
export interface Notification {
    id: string;
    read: boolean;
    sourceUser: Principal;
    entityId: string;
    timestamp: bigint;
    targetUser: Principal;
    eventType: NotificationType;
}
export interface Message {
    id: string;
    content: string;
    read: boolean;
    sender: Principal;
    conversationId: string;
    timestamp: bigint;
    receiver: Principal;
}
export interface ConversationSummary {
    contact: Principal;
    lastMessage?: Message;
    conversationId: string;
    unreadCount: bigint;
}
export interface UserProfile {
    bio: string;
    username: string;
    nftGallery?: Array<string>;
    isDemo: boolean;
    themePreference: ThemePreference;
    links?: Array<ExternalLink>;
    profilePicture?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum NotificationType {
    appRoast = "appRoast",
    like = "like",
    comment = "comment",
    message = "message",
    appUpdate = "appUpdate",
    follow = "follow"
}
export enum PageType {
    notifications = "notifications",
    messages = "messages",
    search = "search",
    discover = "discover",
    profile = "profile"
}
export enum ThemePreference {
    dark = "dark",
    light = "light"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addComment(appId: string, content: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppShowcase(appName: string, description: string, thumbnail: ExternalBlob | null, liveLink: string, category: string, hashtags: Array<string>): Promise<string>;
    editAppShowcase(id: string, appName: string, description: string, thumbnail: ExternalBlob | null, liveLink: string, category: string, hashtags: Array<string>): Promise<void>;
    followUser(target: Principal): Promise<void>;
    generateDemoContent(): Promise<void>;
    getAllAppShowcases(): Promise<Array<AppShowcase>>;
    getAllCategories(): Promise<Array<string>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAnalyticsData(): Promise<AnalyticsData>;
    getAppRoasts(appId: string): Promise<Array<AppRoast>>;
    getAppShowcase(id: string): Promise<AppShowcase | null>;
    getAppsByCategory(category: string): Promise<Array<AppShowcase>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommentsWithUsernames(appId: string): Promise<Array<[Comment, string]>>;
    getFeed(): Promise<Array<AppShowcase>>;
    getFollowers(user: Principal): Promise<Array<Principal>>;
    getFollowersList(user: Principal): Promise<Array<[Principal, UserProfile | null]>>;
    getFollowing(): Promise<Array<Principal>>;
    getFollowingAppShowcases(): Promise<Array<AppShowcase>>;
    getFollowingList(user: Principal): Promise<Array<[Principal, UserProfile | null]>>;
    getGlobalAppFeed(): Promise<Array<AppShowcase>>;
    getMessages(conversationId: string): Promise<Array<Message>>;
    getPageTrafficMetrics(): Promise<Array<PageTraffic>>;
    getThemePreference(): Promise<ThemePreference>;
    getTotalAppsShared(): Promise<bigint>;
    getTotalPageVisits(): Promise<bigint>;
    getTotalProfileCount(): Promise<bigint>;
    getUserAppShowcases(user: Principal): Promise<Array<AppShowcase>>;
    getUserConversations(): Promise<Array<ConversationSummary>>;
    getUserNotifications(): Promise<Array<Notification>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasProfile(user: Principal): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    likeAppShowcase(id: string): Promise<void>;
    markMessageAsRead(messageId: string): Promise<void>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    postAppUpdate(appId: string, updateDescription: string): Promise<void>;
    recordPageVisit(pageType: PageType): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveThemePreference(theme: ThemePreference): Promise<void>;
    searchByAppName(searchTerm: string): Promise<Array<AppShowcase>>;
    searchByHashtag(hashtag: string): Promise<Array<AppShowcase>>;
    searchUsersByUsername(searchTerm: string): Promise<Array<UserProfile>>;
    sendMessage(receiver: Principal, content: string): Promise<string>;
    startConversation(receiver: Principal): Promise<string>;
    submitAppRoast(appId: string, content: string, anonymous: boolean): Promise<string>;
    unfollowUser(target: Principal): Promise<void>;
}
import type { AnalyticsData as _AnalyticsData, AppRoast as _AppRoast, AppShowcase as _AppShowcase, Comment as _Comment, ConversationSummary as _ConversationSummary, ExternalBlob as _ExternalBlob, ExternalLink as _ExternalLink, Message as _Message, Notification as _Notification, NotificationType as _NotificationType, PageTraffic as _PageTraffic, PageType as _PageType, ThemePreference as _ThemePreference, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createAppShowcase(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: string, arg4: string, arg5: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppShowcase(arg0, arg1, await to_candid_opt_n10(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppShowcase(arg0, arg1, await to_candid_opt_n10(this.uploadFile, this.downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async editAppShowcase(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: string, arg5: string, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editAppShowcase(arg0, arg1, arg2, await to_candid_opt_n10(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editAppShowcase(arg0, arg1, arg2, await to_candid_opt_n10(this.uploadFile, this.downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async generateDemoContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDemoContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDemoContent();
            return result;
        }
    }
    async getAllAppShowcases(): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppShowcases();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppShowcases();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAnalyticsData(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return from_candid_AnalyticsData_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return from_candid_AnalyticsData_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppRoasts(arg0: string): Promise<Array<AppRoast>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppRoasts(arg0);
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppRoasts(arg0);
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppShowcase(arg0: string): Promise<AppShowcase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppShowcase(arg0);
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppShowcase(arg0);
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAppsByCategory(arg0: string): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppsByCategory(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppsByCategory(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCommentsWithUsernames(arg0: string): Promise<Array<[Comment, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsWithUsernames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsWithUsernames(arg0);
            return result;
        }
    }
    async getFeed(): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowersList(arg0: Principal): Promise<Array<[Principal, UserProfile | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersList(arg0);
                return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersList(arg0);
            return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFollowing(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing();
            return result;
        }
    }
    async getFollowingAppShowcases(): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingAppShowcases();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingAppShowcases();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFollowingList(arg0: Principal): Promise<Array<[Principal, UserProfile | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingList(arg0);
                return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingList(arg0);
            return from_candid_vec_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGlobalAppFeed(): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalAppFeed();
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalAppFeed();
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getPageTrafficMetrics(): Promise<Array<PageTraffic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageTrafficMetrics();
                return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageTrafficMetrics();
            return from_candid_vec_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getThemePreference(): Promise<ThemePreference> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemePreference();
                return from_candid_ThemePreference_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemePreference();
            return from_candid_ThemePreference_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTotalAppsShared(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAppsShared();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAppsShared();
            return result;
        }
    }
    async getTotalPageVisits(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPageVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPageVisits();
            return result;
        }
    }
    async getTotalProfileCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProfileCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProfileCount();
            return result;
        }
    }
    async getUserAppShowcases(arg0: Principal): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAppShowcases(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAppShowcases(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserConversations();
                return from_candid_vec_n43(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserConversations();
            return from_candid_vec_n43(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotifications();
                return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotifications();
            return from_candid_vec_n47(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async hasProfile(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasProfile(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeAppShowcase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeAppShowcase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeAppShowcase(arg0);
            return result;
        }
    }
    async markMessageAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async postAppUpdate(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postAppUpdate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postAppUpdate(arg0, arg1);
            return result;
        }
    }
    async recordPageVisit(arg0: PageType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPageVisit(to_candid_PageType_n52(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPageVisit(to_candid_PageType_n52(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n54(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n54(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveThemePreference(arg0: ThemePreference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveThemePreference(to_candid_ThemePreference_n56(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveThemePreference(to_candid_ThemePreference_n56(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchByAppName(arg0: string): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByAppName(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByAppName(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async searchByHashtag(arg0: string): Promise<Array<AppShowcase>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByHashtag(arg0);
                return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByHashtag(arg0);
            return from_candid_vec_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async searchUsersByUsername(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByUsername(arg0);
                return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByUsername(arg0);
            return from_candid_vec_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startConversation(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0);
            return result;
        }
    }
    async submitAppRoast(arg0: string, arg1: string, arg2: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppRoast(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppRoast(arg0, arg1, arg2);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
}
function from_candid_AnalyticsData_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsData): AnalyticsData {
    return from_candid_record_n27(uploadFile, downloadFile, value);
}
function from_candid_AppRoast_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRoast): AppRoast {
    return from_candid_record_n35(uploadFile, downloadFile, value);
}
async function from_candid_AppShowcase_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppShowcase): Promise<AppShowcase> {
    return await from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_ConversationSummary_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): ConversationSummary {
    return from_candid_record_n45(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_NotificationType_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n51(uploadFile, downloadFile, value);
}
function from_candid_Notification_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n49(uploadFile, downloadFile, value);
}
function from_candid_PageTraffic_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageTraffic): PageTraffic {
    return from_candid_record_n30(uploadFile, downloadFile, value);
}
function from_candid_PageType_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageType): PageType {
    return from_candid_variant_n32(uploadFile, downloadFile, value);
}
function from_candid_ThemePreference_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThemePreference): ThemePreference {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
async function from_candid_UserProfile_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
async function from_candid_opt_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalLink>]): Array<ExternalLink> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppShowcase]): Promise<AppShowcase | null> {
    return value.length === 0 ? null : await from_candid_AppShowcase_n13(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    thumbnail: [] | [_ExternalBlob];
    hashtags: Array<string>;
    appName: string;
    description: string;
    isDemo: boolean;
    likes: bigint;
    timestamp: bigint;
    category: string;
    liveLink: string;
    comments: Array<_Comment>;
    updateDescription: [] | [string];
    updateTimestamp: [] | [bigint];
}): Promise<{
    id: string;
    creator: Principal;
    thumbnail?: ExternalBlob;
    hashtags: Array<string>;
    appName: string;
    description: string;
    isDemo: boolean;
    likes: bigint;
    timestamp: bigint;
    category: string;
    liveLink: string;
    comments: Array<Comment>;
    updateDescription?: string;
    updateTimestamp?: bigint;
}> {
    return {
        id: value.id,
        creator: value.creator,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n15(uploadFile, downloadFile, value.thumbnail)),
        hashtags: value.hashtags,
        appName: value.appName,
        description: value.description,
        isDemo: value.isDemo,
        likes: value.likes,
        timestamp: value.timestamp,
        category: value.category,
        liveLink: value.liveLink,
        comments: value.comments,
        updateDescription: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.updateDescription)),
        updateTimestamp: record_opt_to_undefined(from_candid_opt_n18(uploadFile, downloadFile, value.updateTimestamp))
    };
}
async function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    nftGallery: [] | [Array<string>];
    isDemo: boolean;
    themePreference: _ThemePreference;
    links: [] | [Array<_ExternalLink>];
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    username: string;
    nftGallery?: Array<string>;
    isDemo: boolean;
    themePreference: ThemePreference;
    links?: Array<ExternalLink>;
    profilePicture?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        username: value.username,
        nftGallery: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.nftGallery)),
        isDemo: value.isDemo,
        themePreference: from_candid_ThemePreference_n23(uploadFile, downloadFile, value.themePreference),
        links: record_opt_to_undefined(from_candid_opt_n25(uploadFile, downloadFile, value.links)),
        profilePicture: record_opt_to_undefined(await from_candid_opt_n15(uploadFile, downloadFile, value.profilePicture))
    };
}
function from_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pageTraffic: Array<_PageTraffic>;
    totalProfiles: bigint;
    totalPageVisits: bigint;
    profileCreations: Array<bigint>;
    totalAppsShared: bigint;
}): {
    pageTraffic: Array<PageTraffic>;
    totalProfiles: bigint;
    totalPageVisits: bigint;
    profileCreations: Array<bigint>;
    totalAppsShared: bigint;
} {
    return {
        pageTraffic: from_candid_vec_n28(uploadFile, downloadFile, value.pageTraffic),
        totalProfiles: value.totalProfiles,
        totalPageVisits: value.totalPageVisits,
        profileCreations: value.profileCreations,
        totalAppsShared: value.totalAppsShared
    };
}
function from_candid_record_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitCount: bigint;
    pageType: _PageType;
    timestamp: bigint;
}): {
    visitCount: bigint;
    pageType: PageType;
    timestamp: bigint;
} {
    return {
        visitCount: value.visitCount,
        pageType: from_candid_PageType_n31(uploadFile, downloadFile, value.pageType),
        timestamp: value.timestamp
    };
}
function from_candid_record_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    appId: string;
    submitter: [] | [Principal];
    anonymous: boolean;
    timestamp: bigint;
}): {
    id: string;
    content: string;
    appId: string;
    submitter?: Principal;
    anonymous: boolean;
    timestamp: bigint;
} {
    return {
        id: value.id,
        content: value.content,
        appId: value.appId,
        submitter: record_opt_to_undefined(from_candid_opt_n36(uploadFile, downloadFile, value.submitter)),
        anonymous: value.anonymous,
        timestamp: value.timestamp
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: Principal;
    lastMessage: [] | [_Message];
    conversationId: string;
    unreadCount: bigint;
}): {
    contact: Principal;
    lastMessage?: Message;
    conversationId: string;
    unreadCount: bigint;
} {
    return {
        contact: value.contact,
        lastMessage: record_opt_to_undefined(from_candid_opt_n46(uploadFile, downloadFile, value.lastMessage)),
        conversationId: value.conversationId,
        unreadCount: value.unreadCount
    };
}
function from_candid_record_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    read: boolean;
    sourceUser: Principal;
    entityId: string;
    timestamp: bigint;
    targetUser: Principal;
    eventType: _NotificationType;
}): {
    id: string;
    read: boolean;
    sourceUser: Principal;
    entityId: string;
    timestamp: bigint;
    targetUser: Principal;
    eventType: NotificationType;
} {
    return {
        id: value.id,
        read: value.read,
        sourceUser: value.sourceUser,
        entityId: value.entityId,
        timestamp: value.timestamp,
        targetUser: value.targetUser,
        eventType: from_candid_NotificationType_n50(uploadFile, downloadFile, value.eventType)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, [] | [_UserProfile]]): Promise<[Principal, UserProfile | null]> {
    return [
        value[0],
        await from_candid_opt_n38(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dark: null;
} | {
    light: null;
}): ThemePreference {
    return "dark" in value ? ThemePreference.dark : "light" in value ? ThemePreference.light : value;
}
function from_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notifications: null;
} | {
    messages: null;
} | {
    search: null;
} | {
    discover: null;
} | {
    profile: null;
}): PageType {
    return "notifications" in value ? PageType.notifications : "messages" in value ? PageType.messages : "search" in value ? PageType.search : "discover" in value ? PageType.discover : "profile" in value ? PageType.profile : value;
}
function from_candid_variant_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRoast: null;
} | {
    like: null;
} | {
    comment: null;
} | {
    message: null;
} | {
    appUpdate: null;
} | {
    follow: null;
}): NotificationType {
    return "appRoast" in value ? NotificationType.appRoast : "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "message" in value ? NotificationType.message : "appUpdate" in value ? NotificationType.appUpdate : "follow" in value ? NotificationType.follow : value;
}
async function from_candid_vec_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppShowcase>): Promise<Array<AppShowcase>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AppShowcase_n13(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n20(uploadFile, downloadFile, x)));
}
function from_candid_vec_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PageTraffic>): Array<PageTraffic> {
    return value.map((x)=>from_candid_PageTraffic_n29(uploadFile, downloadFile, x));
}
function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppRoast>): Array<AppRoast> {
    return value.map((x)=>from_candid_AppRoast_n34(uploadFile, downloadFile, x));
}
async function from_candid_vec_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, [] | [_UserProfile]]>): Promise<Array<[Principal, UserProfile | null]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n42(uploadFile, downloadFile, x)));
}
function from_candid_vec_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Array<ConversationSummary> {
    return value.map((x)=>from_candid_ConversationSummary_n44(uploadFile, downloadFile, x));
}
function from_candid_vec_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n48(uploadFile, downloadFile, x));
}
async function to_candid_ExternalBlob_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_PageType_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageType): _PageType {
    return to_candid_variant_n53(uploadFile, downloadFile, value);
}
function to_candid_ThemePreference_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThemePreference): _ThemePreference {
    return to_candid_variant_n57(uploadFile, downloadFile, value);
}
async function to_candid_UserProfile_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n55(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    nftGallery?: Array<string>;
    isDemo: boolean;
    themePreference: ThemePreference;
    links?: Array<ExternalLink>;
    profilePicture?: ExternalBlob;
}): Promise<{
    bio: string;
    username: string;
    nftGallery: [] | [Array<string>];
    isDemo: boolean;
    themePreference: _ThemePreference;
    links: [] | [Array<_ExternalLink>];
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        username: value.username,
        nftGallery: value.nftGallery ? candid_some(value.nftGallery) : candid_none(),
        isDemo: value.isDemo,
        themePreference: to_candid_ThemePreference_n56(uploadFile, downloadFile, value.themePreference),
        links: value.links ? candid_some(value.links) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n11(uploadFile, downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_variant_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageType): {
    notifications: null;
} | {
    messages: null;
} | {
    search: null;
} | {
    discover: null;
} | {
    profile: null;
} {
    return value == PageType.notifications ? {
        notifications: null
    } : value == PageType.messages ? {
        messages: null
    } : value == PageType.search ? {
        search: null
    } : value == PageType.discover ? {
        discover: null
    } : value == PageType.profile ? {
        profile: null
    } : value;
}
function to_candid_variant_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ThemePreference): {
    dark: null;
} | {
    light: null;
} {
    return value == ThemePreference.dark ? {
        dark: null
    } : value == ThemePreference.light ? {
        light: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}