/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const AppShowcase = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'hashtags' : IDL.Vec(IDL.Text),
  'appName' : IDL.Text,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
  'likes' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'liveLink' : IDL.Text,
  'comments' : IDL.Vec(Comment),
  'updateDescription' : IDL.Opt(IDL.Text),
  'updateTimestamp' : IDL.Opt(IDL.Int),
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'light' : IDL.Null,
});
export const ExternalLink = IDL.Record({
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'nftGallery' : IDL.Opt(IDL.Vec(IDL.Text)),
  'isDemo' : IDL.Bool,
  'themePreference' : ThemePreference,
  'links' : IDL.Opt(IDL.Vec(ExternalLink)),
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const PageType = IDL.Variant({
  'notifications' : IDL.Null,
  'messages' : IDL.Null,
  'search' : IDL.Null,
  'discover' : IDL.Null,
  'profile' : IDL.Null,
});
export const PageTraffic = IDL.Record({
  'visitCount' : IDL.Nat,
  'pageType' : PageType,
  'timestamp' : IDL.Int,
});
export const AnalyticsData = IDL.Record({
  'pageTraffic' : IDL.Vec(PageTraffic),
  'totalProfiles' : IDL.Nat,
  'totalPageVisits' : IDL.Nat,
  'profileCreations' : IDL.Vec(IDL.Int),
  'totalAppsShared' : IDL.Nat,
});
export const AppRoast = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'appId' : IDL.Text,
  'submitter' : IDL.Opt(IDL.Principal),
  'anonymous' : IDL.Bool,
  'timestamp' : IDL.Int,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : IDL.Principal,
  'conversationId' : IDL.Text,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const ConversationSummary = IDL.Record({
  'contact' : IDL.Principal,
  'lastMessage' : IDL.Opt(Message),
  'conversationId' : IDL.Text,
  'unreadCount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'appRoast' : IDL.Null,
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'message' : IDL.Null,
  'appUpdate' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'read' : IDL.Bool,
  'sourceUser' : IDL.Principal,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetUser' : IDL.Principal,
  'eventType' : NotificationType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppShowcase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'editAppShowcase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'generateDemoContent' : IDL.Func([], [], []),
  'getAllAppShowcases' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
  'getAppRoasts' : IDL.Func([IDL.Text], [IDL.Vec(AppRoast)], ['query']),
  'getAppShowcase' : IDL.Func([IDL.Text], [IDL.Opt(AppShowcase)], ['query']),
  'getAppsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(AppShowcase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsWithUsernames' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Comment, IDL.Text))],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowersList' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
      ['query'],
    ),
  'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowingAppShowcases' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
  'getFollowingList' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
      ['query'],
    ),
  'getGlobalAppFeed' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPageTrafficMetrics' : IDL.Func([], [IDL.Vec(PageTraffic)], ['query']),
  'getThemePreference' : IDL.Func([], [ThemePreference], ['query']),
  'getTotalAppsShared' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalPageVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserAppShowcases' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AppShowcase)],
      ['query'],
    ),
  'getUserConversations' : IDL.Func(
      [],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasProfile' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeAppShowcase' : IDL.Func([IDL.Text], [], []),
  'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'postAppUpdate' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordPageVisit' : IDL.Func([PageType], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveThemePreference' : IDL.Func([ThemePreference], [], []),
  'searchByAppName' : IDL.Func([IDL.Text], [IDL.Vec(AppShowcase)], ['query']),
  'searchByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(AppShowcase)], ['query']),
  'searchUsersByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'startConversation' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'submitAppRoast' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Text], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const AppShowcase = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'hashtags' : IDL.Vec(IDL.Text),
    'appName' : IDL.Text,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
    'likes' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'liveLink' : IDL.Text,
    'comments' : IDL.Vec(Comment),
    'updateDescription' : IDL.Opt(IDL.Text),
    'updateTimestamp' : IDL.Opt(IDL.Int),
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'light' : IDL.Null,
  });
  const ExternalLink = IDL.Record({ 'url' : IDL.Text, 'linkLabel' : IDL.Text });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'nftGallery' : IDL.Opt(IDL.Vec(IDL.Text)),
    'isDemo' : IDL.Bool,
    'themePreference' : ThemePreference,
    'links' : IDL.Opt(IDL.Vec(ExternalLink)),
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const PageType = IDL.Variant({
    'notifications' : IDL.Null,
    'messages' : IDL.Null,
    'search' : IDL.Null,
    'discover' : IDL.Null,
    'profile' : IDL.Null,
  });
  const PageTraffic = IDL.Record({
    'visitCount' : IDL.Nat,
    'pageType' : PageType,
    'timestamp' : IDL.Int,
  });
  const AnalyticsData = IDL.Record({
    'pageTraffic' : IDL.Vec(PageTraffic),
    'totalProfiles' : IDL.Nat,
    'totalPageVisits' : IDL.Nat,
    'profileCreations' : IDL.Vec(IDL.Int),
    'totalAppsShared' : IDL.Nat,
  });
  const AppRoast = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'appId' : IDL.Text,
    'submitter' : IDL.Opt(IDL.Principal),
    'anonymous' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : IDL.Principal,
    'conversationId' : IDL.Text,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const ConversationSummary = IDL.Record({
    'contact' : IDL.Principal,
    'lastMessage' : IDL.Opt(Message),
    'conversationId' : IDL.Text,
    'unreadCount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'appRoast' : IDL.Null,
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'message' : IDL.Null,
    'appUpdate' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'read' : IDL.Bool,
    'sourceUser' : IDL.Principal,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetUser' : IDL.Principal,
    'eventType' : NotificationType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppShowcase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'editAppShowcase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'generateDemoContent' : IDL.Func([], [], []),
    'getAllAppShowcases' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
    'getAppRoasts' : IDL.Func([IDL.Text], [IDL.Vec(AppRoast)], ['query']),
    'getAppShowcase' : IDL.Func([IDL.Text], [IDL.Opt(AppShowcase)], ['query']),
    'getAppsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppShowcase)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsWithUsernames' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Comment, IDL.Text))],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowersList' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
        ['query'],
      ),
    'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowingAppShowcases' : IDL.Func(
        [],
        [IDL.Vec(AppShowcase)],
        ['query'],
      ),
    'getFollowingList' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
        ['query'],
      ),
    'getGlobalAppFeed' : IDL.Func([], [IDL.Vec(AppShowcase)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getPageTrafficMetrics' : IDL.Func([], [IDL.Vec(PageTraffic)], ['query']),
    'getThemePreference' : IDL.Func([], [ThemePreference], ['query']),
    'getTotalAppsShared' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalPageVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserAppShowcases' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AppShowcase)],
        ['query'],
      ),
    'getUserConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasProfile' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeAppShowcase' : IDL.Func([IDL.Text], [], []),
    'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'postAppUpdate' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordPageVisit' : IDL.Func([PageType], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveThemePreference' : IDL.Func([ThemePreference], [], []),
    'searchByAppName' : IDL.Func([IDL.Text], [IDL.Vec(AppShowcase)], ['query']),
    'searchByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(AppShowcase)], ['query']),
    'searchUsersByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'startConversation' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'submitAppRoast' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Text], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };