/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'pageTraffic' : Array<PageTraffic>,
  'totalProfiles' : bigint,
  'totalPageVisits' : bigint,
  'profileCreations' : Array<bigint>,
  'totalAppsShared' : bigint,
}
export interface AppRoast {
  'id' : string,
  'content' : string,
  'appId' : string,
  'submitter' : [] | [Principal],
  'anonymous' : boolean,
  'timestamp' : bigint,
}
export interface AppShowcase {
  'id' : string,
  'creator' : Principal,
  'thumbnail' : [] | [ExternalBlob],
  'hashtags' : Array<string>,
  'appName' : string,
  'description' : string,
  'isDemo' : boolean,
  'likes' : bigint,
  'timestamp' : bigint,
  'category' : string,
  'liveLink' : string,
  'comments' : Array<Comment>,
  'updateDescription' : [] | [string],
  'updateTimestamp' : [] | [bigint],
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface ConversationSummary {
  'contact' : Principal,
  'lastMessage' : [] | [Message],
  'conversationId' : string,
  'unreadCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface ExternalLink { 'url' : string, 'linkLabel' : string }
export interface Message {
  'id' : string,
  'content' : string,
  'read' : boolean,
  'sender' : Principal,
  'conversationId' : string,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface Notification {
  'id' : string,
  'read' : boolean,
  'sourceUser' : Principal,
  'entityId' : string,
  'timestamp' : bigint,
  'targetUser' : Principal,
  'eventType' : NotificationType,
}
export type NotificationType = { 'appRoast' : null } |
  { 'like' : null } |
  { 'comment' : null } |
  { 'message' : null } |
  { 'appUpdate' : null } |
  { 'follow' : null };
export interface PageTraffic {
  'visitCount' : bigint,
  'pageType' : PageType,
  'timestamp' : bigint,
}
export type PageType = { 'notifications' : null } |
  { 'messages' : null } |
  { 'search' : null } |
  { 'discover' : null } |
  { 'profile' : null };
export type ThemePreference = { 'dark' : null } |
  { 'light' : null };
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'nftGallery' : [] | [Array<string>],
  'isDemo' : boolean,
  'themePreference' : ThemePreference,
  'links' : [] | [Array<ExternalLink>],
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppShowcase' : ActorMethod<
    [string, string, [] | [ExternalBlob], string, string, Array<string>],
    string
  >,
  'editAppShowcase' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
  'followUser' : ActorMethod<[Principal], undefined>,
  'generateDemoContent' : ActorMethod<[], undefined>,
  'getAllAppShowcases' : ActorMethod<[], Array<AppShowcase>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnalyticsData' : ActorMethod<[], AnalyticsData>,
  'getAppRoasts' : ActorMethod<[string], Array<AppRoast>>,
  'getAppShowcase' : ActorMethod<[string], [] | [AppShowcase]>,
  'getAppsByCategory' : ActorMethod<[string], Array<AppShowcase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsWithUsernames' : ActorMethod<[string], Array<[Comment, string]>>,
  'getFeed' : ActorMethod<[], Array<AppShowcase>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowersList' : ActorMethod<
    [Principal],
    Array<[Principal, [] | [UserProfile]]>
  >,
  'getFollowing' : ActorMethod<[], Array<Principal>>,
  'getFollowingAppShowcases' : ActorMethod<[], Array<AppShowcase>>,
  'getFollowingList' : ActorMethod<
    [Principal],
    Array<[Principal, [] | [UserProfile]]>
  >,
  'getGlobalAppFeed' : ActorMethod<[], Array<AppShowcase>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getPageTrafficMetrics' : ActorMethod<[], Array<PageTraffic>>,
  'getThemePreference' : ActorMethod<[], ThemePreference>,
  'getTotalAppsShared' : ActorMethod<[], bigint>,
  'getTotalPageVisits' : ActorMethod<[], bigint>,
  'getTotalProfileCount' : ActorMethod<[], bigint>,
  'getUserAppShowcases' : ActorMethod<[Principal], Array<AppShowcase>>,
  'getUserConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getUserNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasProfile' : ActorMethod<[Principal], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeAppShowcase' : ActorMethod<[string], undefined>,
  'markMessageAsRead' : ActorMethod<[string], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'postAppUpdate' : ActorMethod<[string, string], undefined>,
  'recordPageVisit' : ActorMethod<[PageType], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveThemePreference' : ActorMethod<[ThemePreference], undefined>,
  'searchByAppName' : ActorMethod<[string], Array<AppShowcase>>,
  'searchByHashtag' : ActorMethod<[string], Array<AppShowcase>>,
  'searchUsersByUsername' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[Principal, string], string>,
  'startConversation' : ActorMethod<[Principal], string>,
  'submitAppRoast' : ActorMethod<[string, string, boolean], string>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];